### ISSUE TITLE
Hotkey Not Working/Crash When Using Hotkey?

### ISSUE THREAD

**Issue by sweetsosweet** [Tristaric/ClassyHats#3]
Hi, I've been trying to open the Classy Hats gui, but the button doesn't do anything. I tried to change the key as well with no results. So I found some hats, and notice they say you can shift+use to open the gui as well, but when I did that, the game crashed. Here is the crashlog:

[https://pastebin.com/z7iKbyjd](https://pastebin.com/z7iKbyjd)

**Comment by ChloeDawn** [comment]
Does this occur in singleplayer or multiplayer? Or both?

**Comment by sweetsosweet** [comment]
I only play singleplayer, I can't help for multi, sorry.

**Comment by yrsegal** [comment]
Have you tried redownloading the mod?

**Comment by yrsegal** [comment]
Also, did you download it from CurseForge, or another site?

**Comment by sweetsosweet** [comment]
I use the Twitch app, so it downloads for me from Curse. Give me a little time, and I'll test the mod alone and see if there's some kind of conflict with another mod.

**Comment by sweetsosweet** [comment]
Tried it again alone, and received the same issue and same crash.

[https://pastebin.com/QUcxmRbx](https://pastebin.com/QUcxmRbx)

**Comment by sweetsosweet** [comment]
Update: I've updated Forge to the new recommended build, and the GUI is now working. I guess having a minimum forge version listed would not go amiss in the future.

**Comment by ChloeDawn** [comment]
We weren't aware that the mod didn't work on older Forge versions. It is advised to use the recommended Forge version when present though, and your version was much older than recommended.
